### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tropixi** [Mr-Proxy-source/nitro-sniper#1]
![image](https://user-images.githubusercontent.com/62711377/151056711-b8666001-eb18-433c-85bb-97d8d5de28be.png)

**Comment by Motzumoto** [comment]
also getting this error, im not sure why people are converting this over to replit when it was fine the way it was before

**Comment by AvaneeshG** [comment]
Npm i discord.jz

**Comment by Mr-Proxy-source** [comment]
Tipe Npm install discord.js before running main.sh
